/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Tools.KoneksiDB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FrMenu extends javax.swing.JFrame {
    
    KoneksiDB getCnn = new KoneksiDB();
    Connection _Cnn;
    
    //tabel user
    String vid_user, vnama_user, vpass, vlev_user;
    String sqlselect;
    /**
     * Creates new form FrManu
     */
    public FrMenu() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | FrMenu.MAXIMIZED_BOTH);
        disabledMenu();
        txtIDUser.requestFocus(true);
    }
    
    public void clearInput(){
        txtIDUser.setText("");
        txtPassword.setText("");
    }
    
    private void disabledMenu(){
        mnSistem.setEnabled(false);
        mnMaster.setEnabled(false);
        mnUser.setEnabled(false);
        mnRetur.setEnabled(false);
        mnLaporan.setEnabled(false);
    }
    
    private void enabledMenu(){
        mnSistem.setEnabled(true);
        mnMaster.setEnabled(true);
        mnUser.setEnabled(true);
        mnRetur.setEnabled(true);
        mnLaporan.setEnabled(true);
    }
    
    void userManager(){
         mnSistem.setVisible(true);
         mnMaster.setVisible(true);
         mnUser.setVisible(true);
         mnRetur.setVisible(true);
         mnLaporan.setVisible(true);
         mnGantiPass.setVisible(false);
    }
    
    void userAdmin(){
         mnSistem.setVisible(true);
         mnMaster.setVisible(true);
         mnUser.setVisible(false);
         mnRetur.setVisible(true);
         mnLaporan.setVisible(true);
    }
    
    private void aksiLogin(){
        if(txtIDUser.getText().equals("") || txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID.User dan Kata Sandi harus diisi!");
            txtIDUser.requestFocus(true);
       }else{
            vid_user = txtIDUser.getText();//memberi nilai pada variable vid_user
            vpass = txtPassword.getText();
            try{
                _Cnn = null;//mengkosongkan koneksi
                _Cnn = getCnn.getConnection(); //membuka koneksi
                sqlselect = "select * from tb_user where ID_USER='"+vid_user+"'"
                        + " and PASS_USER= md5('"+vpass+"') ";
                Statement stat = _Cnn.createStatement();//membuat statement query
                ResultSet res = stat.executeQuery(sqlselect);//menjalankan query
                if(res.first()){//jika hasil query ditemukan
                    vlev_user = res.getString("LEV_USER");//memberikan nilai pada variable vlev_user dari hasil query select kolom lev_user
                    vnama_user = res.getString("NAMA_USER");
                    lblKeterangan.setText("ID. User : "+vid_user+" - "+vnama_user+" | Lev. User : "+vlev_user);
                    panelLogin.setVisible(false);
                    enabledMenu();
                    clearInput();
                    if(vlev_user.equals("Manager")){
                        userManager();
                    }else if(vlev_user.equals("Admin")){
                        userAdmin();
                    }
                    
                }else{
                     JOptionPane.showMessageDialog(this, "ID.User dan Password salah!");
                }
                
            }catch(SQLException se){
                JOptionPane.showMessageDialog(this, "Error method aksiLogin() : " +se);
            }
       }
    }
    
    private void aksiLogout(){
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah anda akan keluar dari sistem?","Informasi",
           JOptionPane.YES_NO_OPTION);
        if(jawab == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblKeterangan = new javax.swing.JLabel();
        panelMenu = new Background.JDesktopPaneGambar();
        panelLogin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnBatal = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtIDUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSistem = new javax.swing.JMenu();
        mnGantiPass = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenu();
        mnDtKategori = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnDtSupplier = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnBarangMskSparepart = new javax.swing.JMenuItem();
        mnBarangMskMotor = new javax.swing.JMenuItem();
        mnBarangKlrSparepart = new javax.swing.JMenuItem();
        mnBarangKlrMotor = new javax.swing.JMenuItem();
        mnPermintaan = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenu();
        mnDtUser = new javax.swing.JMenuItem();
        mnRetur = new javax.swing.JMenu();
        mnReturPnjSparepart = new javax.swing.JMenuItem();
        mnReturPmbSparepart = new javax.swing.JMenuItem();
        mnReturPjnMotor = new javax.swing.JMenuItem();
        mnReturPmbMotor = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnLapSupplier = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        tantang = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: SITORY :.");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblKeterangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblKeterangan.setText("ID. User : ..... | Lev. User : .....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblKeterangan)
                .addContainerGap(911, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKeterangan)
                .addContainerGap())
        );

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        panelLogin.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/0 - login batal.png"))); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login-blue.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtIDUser.setToolTipText("");
        txtIDUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "ID. User"));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Masukan ID. User dan Kata Sandi Anda !");

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kata Sandi"));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Entypo_d83d(0)_64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addComponent(txtIDUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        panelLogin.addTab("LOGIN ", new javax.swing.ImageIcon(getClass().getResource("/Icons/EXY.png")), jPanel2); // NOI18N

        panelMenu.setLayer(panelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        panelLogin.getAccessibleContext().setAccessibleName("");

        mnSistem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1 - Sistem.png"))); // NOI18N
        mnSistem.setText("Sistem");

        mnGantiPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1 - user.png"))); // NOI18N
        mnGantiPass.setText("Ganti Kata Sandi");
        mnGantiPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGantiPassActionPerformed(evt);
            }
        });
        mnSistem.add(mnGantiPass);

        mnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/0 - login batal.png"))); // NOI18N
        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnSistem.add(mnKeluar);

        jMenuBar1.add(mnSistem);

        mnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Master 2.png"))); // NOI18N
        mnMaster.setText("Master");
        mnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMasterActionPerformed(evt);
            }
        });

        mnDtKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Kategori.png"))); // NOI18N
        mnDtKategori.setText("Data Kategori");
        mnDtKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDtKategoriActionPerformed(evt);
            }
        });
        mnMaster.add(mnDtKategori);
        mnMaster.add(jSeparator3);

        mnDtSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Supplier.png"))); // NOI18N
        mnDtSupplier.setText("Data Supplier");
        mnDtSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDtSupplierActionPerformed(evt);
            }
        });
        mnMaster.add(mnDtSupplier);
        mnMaster.add(jSeparator4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Motor.png"))); // NOI18N
        jMenuItem3.setText("Data Motor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Spare_Parts_item.png"))); // NOI18N
        jMenuItem4.setText("Data Sparepart");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem4);

        mnBarangMskSparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/brang masuk.png"))); // NOI18N
        mnBarangMskSparepart.setText("Barang Masuk Sparepart");
        mnBarangMskSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangMskSparepartActionPerformed(evt);
            }
        });
        mnMaster.add(mnBarangMskSparepart);

        mnBarangMskMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/brang masuk.png"))); // NOI18N
        mnBarangMskMotor.setText("Barang Masuk Motor");
        mnBarangMskMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangMskMotorActionPerformed(evt);
            }
        });
        mnMaster.add(mnBarangMskMotor);

        mnBarangKlrSparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Barang keluar.png"))); // NOI18N
        mnBarangKlrSparepart.setText("Barang Keluar Sparepart");
        mnBarangKlrSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangKlrSparepartActionPerformed(evt);
            }
        });
        mnMaster.add(mnBarangKlrSparepart);

        mnBarangKlrMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Barang keluar.png"))); // NOI18N
        mnBarangKlrMotor.setText("Barang Keluar Motor");
        mnBarangKlrMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangKlrMotorActionPerformed(evt);
            }
        });
        mnMaster.add(mnBarangKlrMotor);

        mnPermintaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Permintaan.png"))); // NOI18N
        mnPermintaan.setText("Permintaan Motor");
        mnPermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPermintaanActionPerformed(evt);
            }
        });
        mnMaster.add(mnPermintaan);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Permintaan.png"))); // NOI18N
        jMenuItem12.setText("Permintaan Sparepart");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnMaster.add(jMenuItem12);

        jMenuBar1.add(mnMaster);

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user Icon.png"))); // NOI18N
        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });

        mnDtUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pembayaran-small.png"))); // NOI18N
        mnDtUser.setText("Data User");
        mnDtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDtUserActionPerformed(evt);
            }
        });
        mnUser.add(mnDtUser);

        jMenuBar1.add(mnUser);

        mnRetur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/retur.png"))); // NOI18N
        mnRetur.setText("Retur  ");

        mnReturPnjSparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small1.png"))); // NOI18N
        mnReturPnjSparepart.setText("Retur Penjualan Sparepart");
        mnReturPnjSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReturPnjSparepartActionPerformed(evt);
            }
        });
        mnRetur.add(mnReturPnjSparepart);

        mnReturPmbSparepart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small1.png"))); // NOI18N
        mnReturPmbSparepart.setText("Retur Pembelian Sparepart");
        mnReturPmbSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReturPmbSparepartActionPerformed(evt);
            }
        });
        mnRetur.add(mnReturPmbSparepart);

        mnReturPjnMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small1.png"))); // NOI18N
        mnReturPjnMotor.setText("Retur Penjualan Motor");
        mnReturPjnMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReturPjnMotorActionPerformed(evt);
            }
        });
        mnRetur.add(mnReturPjnMotor);

        mnReturPmbMotor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small1.png"))); // NOI18N
        mnReturPmbMotor.setText("Retur Pembelian Motor");
        mnReturPmbMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReturPmbMotorActionPerformed(evt);
            }
        });
        mnRetur.add(mnReturPmbMotor);

        jMenuBar1.add(mnRetur);

        mnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3 - Mahasiswa.png"))); // NOI18N
        mnLaporan.setText("Laporan");

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem5.setText("Laporan Barang");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem6.setText("Laporan Barang Masuk");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem7.setText("Laporan Barang Keluar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem7);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem11.setText("Laporan Permintaan Barang");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem11);
        mnLaporan.add(jSeparator5);

        mnLapSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        mnLapSupplier.setText("Laporan Supplier");
        mnLapSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapSupplierActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapSupplier);
        mnLaporan.add(jSeparator6);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem9.setText("Laporan Retur Penjualan");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-small2.png"))); // NOI18N
        jMenuItem10.setText("Laporan Retur Pembelian");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnLaporan.add(jMenuItem10);

        jMenuBar1.add(mnLaporan);

        tantang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/about_1.png"))); // NOI18N
        tantang.setText("Tentang");
        tantang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tantangActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/about_aja.png"))); // NOI18N
        jMenuItem2.setText("Tentang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        tantang.add(jMenuItem2);

        jMenuBar1.add(tantang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMenu)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        aksiLogout();
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnDtKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDtKategoriActionPerformed
        FrKategori fr = new FrKategori();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnDtKategoriActionPerformed

    private void mnDtSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDtSupplierActionPerformed
        IfrSupplier fr = new IfrSupplier();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnDtSupplierActionPerformed

    private void mnBarangMskSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangMskSparepartActionPerformed
        IfrBarangSparePartMasuk fr = new IfrBarangSparePartMasuk();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnBarangMskSparepartActionPerformed

    private void mnBarangKlrSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangKlrSparepartActionPerformed
        IfrBarangSparePartKeluar fr = new IfrBarangSparePartKeluar();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnBarangKlrSparepartActionPerformed

    private void mnPermintaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPermintaanActionPerformed
        IfrPermintaanBarangMotor fr = new IfrPermintaanBarangMotor();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnPermintaanActionPerformed

    private void mnReturPnjSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReturPnjSparepartActionPerformed
        FrReturPenjualanSpare fr = new FrReturPenjualanSpare();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnReturPnjSparepartActionPerformed

    private void mnReturPmbMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReturPmbMotorActionPerformed
        IfrReturPembelianMotor fr = new IfrReturPembelianMotor();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnReturPmbMotorActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        IfrLaporanBarang fr = new IfrLaporanBarang();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        IfrLaporanBrgMasuk fr = new IfrLaporanBrgMasuk();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        IfrLaporanBrgKeluar fr = new IfrLaporanBrgKeluar();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrLapPermintaanBarang fr = new FrLapPermintaanBarang();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void mnLapSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapSupplierActionPerformed
        IfrLaporanSupplier fr = new IfrLaporanSupplier();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnLapSupplierActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
         FrLapReturPenjualan fr = new FrLapReturPenjualan();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        IfrLapReturPembelian fr = new IfrLapReturPembelian();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void tantangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tantangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tantangActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        aksiLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        aksiLogin();
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void mnGantiPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGantiPassActionPerformed
        IfrGantiPass fr = new IfrGantiPass();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnGantiPassActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnUserActionPerformed

    private void mnDtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDtUserActionPerformed
        IfrUser fr = new IfrUser();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnDtUserActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrMotor1 fr = new FrMotor1();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        IfrPermintaanBarangSparepart fr = new IfrPermintaanBarangSparepart();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void mnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnMasterActionPerformed

    private void mnBarangMskMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangMskMotorActionPerformed
        IfrBarangMotorMasuk fr = new IfrBarangMotorMasuk();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnBarangMskMotorActionPerformed

    private void mnBarangKlrMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangKlrMotorActionPerformed
        IfrBarangMotorKeluar fr = new IfrBarangMotorKeluar();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnBarangKlrMotorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        IfrSparepart fr = new IfrSparepart();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnReturPmbSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReturPmbSparepartActionPerformed
        IfrReturPembelianSparepart fr = new IfrReturPembelianSparepart();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnReturPmbSparepartActionPerformed

    private void mnReturPjnMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReturPjnMotorActionPerformed
        FrReturPenjualanMotor fr = new FrReturPenjualanMotor();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_mnReturPjnMotorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tentang fr = new Tentang();
        panelMenu.add(fr);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JMenuItem mnBarangKlrMotor;
    private javax.swing.JMenuItem mnBarangKlrSparepart;
    private javax.swing.JMenuItem mnBarangMskMotor;
    private javax.swing.JMenuItem mnBarangMskSparepart;
    private javax.swing.JMenuItem mnDtKategori;
    private javax.swing.JMenuItem mnDtSupplier;
    private javax.swing.JMenuItem mnDtUser;
    private javax.swing.JMenuItem mnGantiPass;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnLapSupplier;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnPermintaan;
    private javax.swing.JMenu mnRetur;
    private javax.swing.JMenuItem mnReturPjnMotor;
    private javax.swing.JMenuItem mnReturPmbMotor;
    private javax.swing.JMenuItem mnReturPmbSparepart;
    private javax.swing.JMenuItem mnReturPnjSparepart;
    private javax.swing.JMenu mnSistem;
    private javax.swing.JMenu mnUser;
    private javax.swing.JTabbedPane panelLogin;
    private javax.swing.JDesktopPane panelMenu;
    private javax.swing.JMenu tantang;
    private javax.swing.JTextField txtIDUser;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
